-- type function Freeze<T>(target: T)
	
-- end

-- type keysMethod <T> = (self: T) -> ()
-- type valuesMethod = () -> ()
-- type entriesMethod = () -> ()
-- type hasMethod = () -> ()
-- type assignMethod = () -> ()
-- type mergeMethod = () -> ()
-- type freezeMethod = () -> ()
-- type unfreezeMethod = () -> ()
-- type sealMethod = () -> ()
-- type unsealMethod = () -> ()

-- export type NewTable<T> = {
-- 	keys: keysMethod<T>,
-- 	values: valuesMethod,
-- 	entries: entriesMethod,
-- 	has: hasMethod,
-- 	assign: assignMethod,
-- 	merge: mergeMethod,
-- 	freeze: freezeMethod,
-- 	unfreeze: unfreezeMethod,
-- 	seal: sealMethod,
-- 	unseal: unsealMethod,
-- }

-- export type ConstructorMethods = {
-- 	New: <Args>(Args) -> NewTable<Args> & Args,
-- }

-- type Profile = {
--     read id: number,
-- }

-- return {}
